favicon: null
name: Netzwerkkunde
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.08960573
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#5B90E1'
    - '#6E3930'
    - '#151518'
    - '#CF6443'
    - '#ACC4E2'
  lightness: 1
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
